# Generated by Django 5.2 on 2025-04-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_key', models.CharField(max_length=255)),
                ('processed_key', models.CharField(blank=True, max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('original_size', models.CharField(blank=True, max_length=50)),
                ('processed_size', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
